# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish to Github Page

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    env: 
      GH_PAT: ${{secrets.GH_PAT}}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run build
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.0.1
      with:
        target_branch: gh-pages
        keep_history: true
        allow_empty_commit: true
        build_dir: dist
        author: caxerx <webmaster@caxerx.com>
        committer: caxerx <webmaster@caxerx.com>
        fqdn: harvest.iw.gy
